### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by m038**
Standalone bundle for PR https://github.com/superdesk/web-renderer/pull/15

### CODE REVIEW

**Comment by ahilles107** [comment]
lock is not needed in bundle

**Comment by m038** [comment]
Removed.

**Comment by ahilles107** [comment]
Please fix also broken tests: https://travis-ci.org/SuperdeskWebPublisher/SWPBridgeBundle/builds/77018053

**Comment by m038** [comment]
I've fixed the tests now.

**Pull request merged**
